<Workspace Version="0.8.2.2223" X="-604.576011258022" Y="-275.358444123147" zoom="1.53587878889713" Name="Room.Boundaries" Description="Gets a list of all boundary elements of a given room or area" ID="fb07f5d8-94b8-4985-bf2f-a54fe832aa66" Category="Clockwork.Revit.Elements.Room.Query">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Nodes.Symbol guid="981a0e03-9fe7-44f9-9504-2ea77ca18745" type="Dynamo.Nodes.Symbol" nickname="Input" x="509.3761100198" y="441.905667948897" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True">
      <Symbol value="Room(s)" />
    </Dynamo.Nodes.Symbol>
    <Dynamo.Nodes.Output guid="aa6058d6-2d2c-419c-adc4-23f58c7f5767" type="Dynamo.Nodes.Output" nickname="Output" x="900.550720573058" y="395.769478770684" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False">
      <Symbol value="Elements" />
    </Dynamo.Nodes.Output>
    <Dynamo.Nodes.Output guid="d71efcb4-3df8-472f-b598-63d7a11c097e" type="Dynamo.Nodes.Output" nickname="Output" x="917.504146875623" y="477.49665251581" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False">
      <Symbol value="Curves" />
    </Dynamo.Nodes.Output>
    <DSIronPythonNode.PythonNode guid="9749f625-ba3d-4c2e-be38-9b18c2fc22f3" type="DSIronPythonNode.PythonNode" nickname="Python Script" x="683.605247195924" y="436.699326054071" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" inputcount="1">
      <Script># Copyright(c) 2015, Andreas Dieckmann
# @a_dieckmann, https://github.com/CAAD-RWTH/ClockworkForDynamo
# Copyright(c) 2015, Konrad K Sobon
# @arch_laboratory, http://archi-lab.net
# This node was originally created by Andreas. Thank you!

import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *
import Autodesk

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.GeometryConversion)

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager

doc = DocumentManager.Instance.CurrentDBDocument

import sys
pyt_path = r'C:\Program Files (x86)\IronPython 2.7\Lib'
sys.path.append(pyt_path)

if isinstance(IN[0], list):
	items = []
	for i in IN[0]:
		items.append(UnwrapElement(i))
else:
	items = UnwrapElement(IN[0])

def GetRoomBoundary(doc, item, options):
	eList = []
	cList = []
	try:
		for i in item.GetBoundarySegments(options):
			for j in i:
				eList.append(doc.GetElement(j.ElementId))
				cList.append(j.Curve.ToProtoType())
	except:
		try:
			results = calculator.CalculateSpatialElementGeometry(item)
			for face in results.GetGeometry().Faces:
				for bface in results.GetBoundaryFaceInfo(face):
					eList.append(doc.GetElement(bface.SpatialBoundaryElement.HostElementId))
		except:
			pass
	return [eList, cList]

try:
	errorReport = None
	calculator = SpatialElementGeometryCalculator(doc)
	options = Autodesk.Revit.DB.SpatialElementBoundaryOptions()
	# get boundary location from area computation settings
	boundloc = Autodesk.Revit.DB.AreaVolumeSettings.GetAreaVolumeSettings(doc).GetSpatialElementBoundaryLocation(SpatialElementType.Room)
	options.SpatialElementBoundaryLocation = boundloc
	elementlist, curvelist = [], []
	if isinstance(items, list):
		for item in items:
			elementlist.append(GetRoomBoundary(doc, item, options)[0])
			curvelist.append(GetRoomBoundary(doc, item, options)[1])
	else:
		elementlist = GetRoomBoundary(doc, items, options)[0]
		curvelist = GetRoomBoundary(doc, items, options)[1]
except:
	# if error accurs anywhere in the process catch it
	import traceback
	errorReport = traceback.format_exc()
		
#Assign your output to the OUT variable
if errorReport == None:
	OUT = [elementlist,curvelist]
else:
	OUT = errorReport</Script>
    </DSIronPythonNode.PythonNode>
  </Elements>
  <Connectors>
    <Dynamo.Models.ConnectorModel start="981a0e03-9fe7-44f9-9504-2ea77ca18745" start_index="0" end="9749f625-ba3d-4c2e-be38-9b18c2fc22f3" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="9749f625-ba3d-4c2e-be38-9b18c2fc22f3" start_index="0" end="aa6058d6-2d2c-419c-adc4-23f58c7f5767" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="9749f625-ba3d-4c2e-be38-9b18c2fc22f3" start_index="0" end="d71efcb4-3df8-472f-b598-63d7a11c097e" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="background_preview" eyeX="35.8100929260254" eyeY="103.221809387207" eyeZ="104.000068664551" lookX="-35.8100929260254" lookY="-98.221809387207" lookZ="-104.000068664551" />
  </Cameras>
</Workspace>
