<Workspace Version="1.0.0.1180" X="113.164215686275" Y="30" zoom="0.50796568627451" Name="Home" Description="" RunType="Manual" RunPeriod="1000" HasRunWithoutCrash="True">
  <NamespaceResolutionMap />
  <Elements>
    <DSRevitNodesUI.ElementsOfCategory guid="4678a54c-cc18-4f22-a339-57c808ddba57" type="DSRevitNodesUI.ElementsOfCategory" nickname="All Elements of Category" x="345" y="611.5" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" />
    <DSRevitNodesUI.Categories guid="cd101fbb-4094-48b8-835a-01b0591e413f" type="DSRevitNodesUI.Categories" nickname="Categories" x="-36" y="611.5" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false" index="470:Topography" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="3825b025-aa92-49f0-b7dd-ab690f6875c0" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="List.FirstItem" x="613" y="611.5" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="DSCoreNodes.dll" function="DSCore.List.FirstItem@var[]..[]" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="62c4a49a-2a15-41cd-9641-40e025e9b2f3" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Topography.Mesh" x="819" y="583.5" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="RevitNodes.dll" function="Revit.Elements.Topography.Mesh" />
    <Dynamo.Graph.Nodes.CustomNodes.Function guid="6400db5a-de6e-4170-b742-53d20b18856c" type="Dynamo.Graph.Nodes.CustomNodes.Function" nickname="Mesh.IntersectionWithPlane" x="1081" y="503.5" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <ID value="b922a271-0699-4c95-9f75-2b8e213c169f" />
      <Name value="Mesh.IntersectionWithPlane" />
      <Description value="Calculates the intersection of a mesh and a plane" />
      <Inputs>
        <Input value="plane" />
        <Input value="mesh" />
      </Inputs>
      <Outputs>
        <Output value="points" />
        <Output value="polyCurve" />
        <Output value="nurbsCurveByPoints" />
        <Output value="nurbsCurveByControlPoints" />
      </Outputs>
    </Dynamo.Graph.Nodes.CustomNodes.Function>
    <Dynamo.Graph.Nodes.CustomNodes.Function guid="6b2c6606-3883-4f2f-b44e-d135f856a567" type="Dynamo.Graph.Nodes.CustomNodes.Function" nickname="Mesh.FaceVertices" x="1081" y="1150.5" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <ID value="21e0126f-dca2-47a0-84f3-b403bc0e6d71" />
      <Name value="Mesh.FaceVertices" />
      <Description value="Gets the vertices of each face of a given mesh" />
      <Inputs>
        <Input value="mesh" />
      </Inputs>
      <Outputs>
        <Output value="vertices" />
      </Outputs>
    </Dynamo.Graph.Nodes.CustomNodes.Function>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="7b5035d0-c204-4ce7-83d5-d82a481735ea" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Point.Origin" x="613" y="394.5" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Point.Origin" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="2b47d468-48c1-4388-95fd-ea0b1b10e279" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Vector.XAxis" x="613" y="502.5" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Vector.XAxis" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="9ea7e51b-4393-4389-9608-98efe08e511b" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Plane.ByOriginNormal" x="819" y="449.5" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Plane.ByOriginNormal@Autodesk.DesignScript.Geometry.Point,Autodesk.DesignScript.Geometry.Vector" />
    <CoreNodeModels.Watch guid="7ed2a0bd-6bac-42c9-b7fa-516570989781" type="CoreNodeModels.Watch" nickname="Watch" x="2090" y="-41.5" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" />
    <CoreNodeModels.Watch guid="bfe01b71-2650-4fb0-a4e6-9578fefd295d" type="CoreNodeModels.Watch" nickname="Watch" x="2090" y="830.5" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" />
    <CoreNodeModels.Watch guid="aadba8d8-a539-48c5-b6a7-c1c1568a13f2" type="CoreNodeModels.Watch" nickname="Watch" x="1434" y="377.5" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" />
    <CoreNodeModels.Watch guid="9b55054f-f428-45a6-844a-1c6bcf095888" type="CoreNodeModels.Watch" nickname="Watch" x="2090" y="707.5" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" />
    <CoreNodeModels.Watch guid="8731ec91-1d71-4d59-88a3-4cfb00eca7fc" type="CoreNodeModels.Watch" nickname="Watch" x="1434" y="1150.5" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" />
    <Watch3DNodeModels.Watch3D guid="8627f293-feba-44b1-bf42-56a8c51ae0b3" type="Watch3DNodeModels.Watch3D" nickname="Watch 3D" x="2090" y="351.5" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <view width="210" height="263">
        <Camera Name="8627f293-feba-44b1-bf42-56a8c51ae0b3 Preview" eyeX="-20.6876305845023" eyeY="22.4115997998775" eyeZ="99.9902144917612" lookX="20.6876305845023" lookY="-22.4115997998775" lookZ="-99.9902144917612" upX="0" upY="1" upZ="0" />
        <Camera Name="8627f293-feba-44b1-bf42-56a8c51ae0b3 Preview" eyeX="-20.6876305845023" eyeY="22.4115997998775" eyeZ="99.9902144917612" lookX="20.6876305845023" lookY="-22.4115997998775" lookZ="-99.9902144917612" upX="0" upY="1" upZ="0" />
      </view>
    </Watch3DNodeModels.Watch3D>
    <CoreNodeModels.CreateList guid="6341f224-01c2-4dbf-9d73-7b4eee35e23a" type="CoreNodeModels.CreateList" nickname="List.Create" x="1824" y="351.5" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="2" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="145e55cc-8e2d-42c9-b47d-28209c12ef64" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Surface.ByPerimeterPoints" x="1824" y="1150.5" isVisible="true" isUpstreamVisible="false" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Surface.ByPerimeterPoints@Autodesk.DesignScript.Geometry.Point[]" />
    <CoreNodeModels.Watch guid="b836bbf6-2c4a-4b15-b073-130d86c8cb55" type="CoreNodeModels.Watch" nickname="Watch" x="2090" y="953.5" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" />
    <Watch3DNodeModels.Watch3D guid="42f9b7c1-8a4e-40b6-9e36-a582254d1fce" type="Watch3DNodeModels.Watch3D" nickname="Watch 3D" x="2090" y="1347.5" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <view width="210" height="263">
        <Camera Name="42f9b7c1-8a4e-40b6-9e36-a582254d1fce Preview" eyeX="-20.6876305845023" eyeY="22.4115997998775" eyeZ="99.9902144917612" lookX="20.6876305845023" lookY="-22.4115997998775" lookZ="-99.9902144917612" upX="0" upY="1" upZ="0" />
        <Camera Name="42f9b7c1-8a4e-40b6-9e36-a582254d1fce Preview" eyeX="-20.6876305845023" eyeY="22.4115997998775" eyeZ="99.9902144917612" lookX="20.6876305845023" lookY="-22.4115997998775" lookZ="-99.9902144917612" upX="0" upY="1" upZ="0" />
      </view>
    </Watch3DNodeModels.Watch3D>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="4678a54c-cc18-4f22-a339-57c808ddba57" start_index="0" end="3825b025-aa92-49f0-b7dd-ab690f6875c0" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="cd101fbb-4094-48b8-835a-01b0591e413f" start_index="0" end="4678a54c-cc18-4f22-a339-57c808ddba57" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="3825b025-aa92-49f0-b7dd-ab690f6875c0" start_index="0" end="62c4a49a-2a15-41cd-9641-40e025e9b2f3" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="62c4a49a-2a15-41cd-9641-40e025e9b2f3" start_index="0" end="6400db5a-de6e-4170-b742-53d20b18856c" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="62c4a49a-2a15-41cd-9641-40e025e9b2f3" start_index="0" end="6b2c6606-3883-4f2f-b44e-d135f856a567" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="62c4a49a-2a15-41cd-9641-40e025e9b2f3" start_index="0" end="6341f224-01c2-4dbf-9d73-7b4eee35e23a" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="6400db5a-de6e-4170-b742-53d20b18856c" start_index="0" end="7ed2a0bd-6bac-42c9-b7fa-516570989781" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="6400db5a-de6e-4170-b742-53d20b18856c" start_index="1" end="9b55054f-f428-45a6-844a-1c6bcf095888" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="6400db5a-de6e-4170-b742-53d20b18856c" start_index="2" end="aadba8d8-a539-48c5-b6a7-c1c1568a13f2" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="6400db5a-de6e-4170-b742-53d20b18856c" start_index="3" end="bfe01b71-2650-4fb0-a4e6-9578fefd295d" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="6b2c6606-3883-4f2f-b44e-d135f856a567" start_index="0" end="8731ec91-1d71-4d59-88a3-4cfb00eca7fc" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="7b5035d0-c204-4ce7-83d5-d82a481735ea" start_index="0" end="9ea7e51b-4393-4389-9608-98efe08e511b" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="2b47d468-48c1-4388-95fd-ea0b1b10e279" start_index="0" end="9ea7e51b-4393-4389-9608-98efe08e511b" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="9ea7e51b-4393-4389-9608-98efe08e511b" start_index="0" end="6400db5a-de6e-4170-b742-53d20b18856c" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="aadba8d8-a539-48c5-b6a7-c1c1568a13f2" start_index="0" end="6341f224-01c2-4dbf-9d73-7b4eee35e23a" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="8731ec91-1d71-4d59-88a3-4cfb00eca7fc" start_index="0" end="145e55cc-8e2d-42c9-b47d-28209c12ef64" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="6341f224-01c2-4dbf-9d73-7b4eee35e23a" start_index="0" end="8627f293-feba-44b1-bf42-56a8c51ae0b3" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="145e55cc-8e2d-42c9-b47d-28209c12ef64" start_index="0" end="b836bbf6-2c4a-4b15-b073-130d86c8cb55" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="145e55cc-8e2d-42c9-b47d-28209c12ef64" start_index="0" end="42f9b7c1-8a4e-40b6-9e36-a582254d1fce" end_index="0" portType="0" />
  </Connectors>
  <Notes>
    <Dynamo.Graph.Notes.NoteModel guid="753ea6fc-e0ae-4fa5-9c3e-3670066388e7" text="You'll need to run this graph on top of a Revit file that contains a toposurface, e.g. the basic architectural sample project that ships with Revit." x="-36" y="543.5" />
  </Notes>
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Hintergrundvorschau" eyeX="-19228.9056463618" eyeY="19582.7681649667" eyeZ="105229.559507901" lookX="21503.0676269542" lookY="-23294.9899292004" lookZ="-103931.493530278" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>