<Workspace Version="1.3.1.1736" X="140.594166163503" Y="146.308123562663" zoom="0.932547478716438" ScaleFactor="1" Name="Home" Description="" RunType="Manual" RunPeriod="1000" HasRunWithoutCrash="True">
  <NamespaceResolutionMap />
  <Elements>
    <DSRevitNodesUI.Views guid="ff3d17e5-d83e-4db0-bc69-b5c4aff22208" type="DSRevitNodesUI.Views" nickname="Views" x="287.40639625585" y="146.260530421217" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false" index="21:Section Perspective" />
    <Dynamo.Graph.Nodes.CustomNodes.Function guid="38aaac9a-d749-426b-8d4e-b4eaa64e0ca6" type="Dynamo.Graph.Nodes.CustomNodes.Function" nickname="PerspectiveView.OrientToEyeAndTargetPosition" x="544.36496367158" y="230.175558511105" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <PortInfo index="2" default="False" />
      <ID value="161bade3-e592-4aff-a1f7-0a49f2f92bab" />
      <Name value="PerspectiveView.OrientToEyeAndTargetPosition" />
      <Description value="Sets the orientation of a given perspective view based on a given eye and target position. View needs to be in an unlocked state." />
      <Inputs>
        <Input value="view" />
        <Input value="eyePosition" />
        <Input value="targetPosition" />
      </Inputs>
      <Outputs>
        <Output value="View" />
        <Output value="success" />
      </Outputs>
    </Dynamo.Graph.Nodes.CustomNodes.Function>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="7c242c39-058b-4857-982e-efce5961a6f5" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Point.Origin" x="369.97591872776" y="406.681878735824" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Point.Origin" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="ec944a80-5012-4a5e-84d7-79517e62fa48" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Point.ByCoordinates" x="287.40639625585" y="255.260530421217" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Point.ByCoordinates@double,double,double">
      <PortInfo index="0" default="True" />
      <PortInfo index="1" default="True" />
      <PortInfo index="2" default="True" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <CoreNodeModels.Input.DoubleSlider guid="a5d9667a-735c-4bf8-a156-b8b3c803cbf3" type="CoreNodeModels.Input.DoubleSlider" nickname="Number Slider" x="-118.59360374415" y="198.260530421217" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <System.Double>66.5557762933418</System.Double>
      <Range min="0" max="100" step="0.1" />
    </CoreNodeModels.Input.DoubleSlider>
    <CoreNodeModels.Input.DoubleSlider guid="fa4b3637-74e8-4f5a-8005-3d6855badc7e" type="CoreNodeModels.Input.DoubleSlider" nickname="Number Slider" x="-118.59360374415" y="281.260530421217" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <System.Double>84.9793258582295</System.Double>
      <Range min="0" max="100" step="0.1" />
    </CoreNodeModels.Input.DoubleSlider>
    <CoreNodeModels.Input.DoubleSlider guid="63f5def8-bfec-415b-b24f-74706179cb01" type="CoreNodeModels.Input.DoubleSlider" nickname="Number Slider" x="-118.59360374415" y="364.260530421217" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <System.Double>49.2026359510874</System.Double>
      <Range min="0" max="100" step="0.1" />
    </CoreNodeModels.Input.DoubleSlider>
    <CoreNodeModels.Watch guid="de701279-255d-4fb5-8f4f-723ccd58ecf0" type="CoreNodeModels.Watch" nickname="Watch" x="996.160609738996" y="152.967693342565" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
    </CoreNodeModels.Watch>
    <CoreNodeModels.Watch guid="3d9a2a81-e88d-4aff-9b21-dd2683c368ac" type="CoreNodeModels.Watch" nickname="Watch" x="1004.08476704237" y="319.877103454925" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
    </CoreNodeModels.Watch>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="ff3d17e5-d83e-4db0-bc69-b5c4aff22208" start_index="0" end="38aaac9a-d749-426b-8d4e-b4eaa64e0ca6" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="38aaac9a-d749-426b-8d4e-b4eaa64e0ca6" start_index="0" end="de701279-255d-4fb5-8f4f-723ccd58ecf0" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="38aaac9a-d749-426b-8d4e-b4eaa64e0ca6" start_index="1" end="3d9a2a81-e88d-4aff-9b21-dd2683c368ac" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="7c242c39-058b-4857-982e-efce5961a6f5" start_index="0" end="38aaac9a-d749-426b-8d4e-b4eaa64e0ca6" end_index="2" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="ec944a80-5012-4a5e-84d7-79517e62fa48" start_index="0" end="38aaac9a-d749-426b-8d4e-b4eaa64e0ca6" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="a5d9667a-735c-4bf8-a156-b8b3c803cbf3" start_index="0" end="ec944a80-5012-4a5e-84d7-79517e62fa48" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="fa4b3637-74e8-4f5a-8005-3d6855badc7e" start_index="0" end="ec944a80-5012-4a5e-84d7-79517e62fa48" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="63f5def8-bfec-415b-b24f-74706179cb01" start_index="0" end="ec944a80-5012-4a5e-84d7-79517e62fa48" end_index="2" portType="0" />
  </Connectors>
  <Notes>
    <Dynamo.Graph.Notes.NoteModel guid="150d974d-219e-4f89-b122-4ed0cecebea8" text="You can use the Sample Architecture Project (Basic) that ships with Revit to run this graph." x="287.40639625585" y="92.2605304212169" />
  </Notes>
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Hintergrundvorschau" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>