{
  "Uuid": "3c9d0464-8643-5ffe-96e5-ab1769818209",
  "IsCustomNode": false,
  "Description": "",
  "Name": "Geometry.Curves",
  "ElementResolver": {
    "ResolutionMap": {}
  },
  "Inputs": [],
  "Outputs": [],
  "Nodes": [
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CodeBlockNodeModel, DynamoCore",
      "NodeType": "CodeBlockNode",
      "Code": "1;",
      "Id": "84eb4267d7424dc8b663d2643ad140bf",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "918ae50b91cf47259db509c9cfc00df7",
          "Name": "",
          "Description": "Wert des Ausdrucks in Zeile 1",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Erm√∂glicht die direkte Erstellung von DesignScript-Code."
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Point.ByCoordinates@double,double",
      "Id": "c3d18560a89f4cbf9dde858c1a7b9d38",
      "Inputs": [
        {
          "Id": "57356f9bf43341d6a987aed7574913c3",
          "Name": "x",
          "Description": "double\nVorgabewert : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "e53aa12fe9ba42a1bacec4c23fda372c",
          "Name": "y",
          "Description": "double\nVorgabewert : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "b8d4cd4105654efdb5846c2029dda407",
          "Name": "Point",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Legt einen Punkt in der XY-Ebene nach Angabe zweier kartesischer Koordinaten fest. Die Z-Komponente hat den Wert 0.\n\nPoint.ByCoordinates (x: double = 0, y: double = 0): Point"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Point.ByCoordinates@double,double",
      "Id": "6f02d94ddfcf4c58ae3ea011cb7ab0fa",
      "Inputs": [
        {
          "Id": "90d7d1d8ec274bb397d574c27ec70a08",
          "Name": "x",
          "Description": "double\nVorgabewert : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "031dafa2368542ec95734e03b67ec9d6",
          "Name": "y",
          "Description": "double\nVorgabewert : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "15e6315e36154c5a947efbb971f18d3f",
          "Name": "Point",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Legt einen Punkt in der XY-Ebene nach Angabe zweier kartesischer Koordinaten fest. Die Z-Komponente hat den Wert 0.\n\nPoint.ByCoordinates (x: double = 0, y: double = 0): Point"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Point.ByCoordinates@double,double",
      "Id": "8fe5b45aae6f4d46a231b15e5fe59fb7",
      "Inputs": [
        {
          "Id": "b2e60b7f56f149148125a1e8a9d87d6a",
          "Name": "x",
          "Description": "double\nVorgabewert : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "e3071655713f45eea31618facc988e57",
          "Name": "y",
          "Description": "double\nVorgabewert : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "659697cab2ff42d8ae75500195209c29",
          "Name": "Point",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Legt einen Punkt in der XY-Ebene nach Angabe zweier kartesischer Koordinaten fest. Die Z-Komponente hat den Wert 0.\n\nPoint.ByCoordinates (x: double = 0, y: double = 0): Point"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Point.Origin",
      "Id": "b0583fafe5f843c08750b1de86bbcf28",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "b3e996821b9e4fa28e49877f402043ac",
          "Name": "Point",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Ruft den Ursprung ab (0,0,0).\n\nPoint.Origin ( ): Point"
    },
    {
      "ConcreteType": "CoreNodeModels.CreateList, CoreNodeModels",
      "VariableInputPorts": true,
      "NodeType": "ExtensionNode",
      "Id": "ec3ec5237d54449eabc489df3b88791f",
      "Inputs": [
        {
          "Id": "aac8cd0817204e4292f95e491ea8e988",
          "Name": "item0",
          "Description": "Elementindex #0",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "8bfb349fd56e4bad8c612abeb53fe127",
          "Name": "item1",
          "Description": "Elementindex #1",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "444107172e4d4bb0bca8be6241e413bf",
          "Name": "item2",
          "Description": "Elementindex #2",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "a58890fe27ac4c198eacc15d07c97b20",
          "Name": "item3",
          "Description": "Elementindex #3",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "3cb08e0c99f146729fb38281b66a403f",
          "Name": "list",
          "Description": "Eine Liste",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Erstellt eine neue Liste aus den angegebenen Eingaben."
    },
    {
      "ConcreteType": "CoreNodeModels.Watch, CoreNodeModels",
      "NodeType": "ExtensionNode",
      "Id": "ef6d8e2bd41f4c9baac5d0ed844bf4c8",
      "Inputs": [
        {
          "Id": "4af964687c3a49148c2c6fa12e6ced66",
          "Name": "",
          "Description": "Auszuwertender Block",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "590c08a6b28a439cbd6f4e96702f3dba",
          "Name": "",
          "Description": "Inhalt beobachten",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Visualisierung der Ausgabe des Blocks"
    },
    {
      "ConcreteType": "Watch3DNodeModels.Watch3D, Watch3DNodeModels",
      "WatchWidth": 220.0,
      "WatchHeight": 326.0,
      "WasExecuted": true,
      "Camera": {
        "Name": "c1a0c5e9-831b-4e0c-8704-652351045d80 Preview",
        "EyeX": -17.0,
        "EyeY": 24.0,
        "EyeZ": 50.0,
        "LookX": 12.0,
        "LookY": -13.0,
        "LookZ": -58.0,
        "UpX": 0.0,
        "UpY": 1.0,
        "UpZ": 0.0
      },
      "NodeType": "ExtensionNode",
      "Id": "c1a0c5e9831b4e0c8704652351045d80",
      "Inputs": [
        {
          "Id": "e29f9a7fc7f64996997faa7e564b61aa",
          "Name": "",
          "Description": "Eingehende Geometrieobjekte",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "4cf85227410549e3945d98068d6918fc",
          "Name": "",
          "Description": "Eingehende Geometrieobjekte",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Zeigt eine dynamische Vorschau der Geometrie an."
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CustomNodes.Function, DynamoCore",
      "FunctionSignature": "576880d2-5f2c-4e34-9183-359361aaa077",
      "FunctionType": "Graph",
      "NodeType": "FunctionNode",
      "Id": "7e857513e74e46098f893ffaefac76fd",
      "Inputs": [
        {
          "Id": "6b2093d9449b41d9b52d150f0ade8ce1",
          "Name": "points",
          "Description": "Point[]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "0163d8a6b32046ce8e318600f2e384ec",
          "Name": "Curves",
          "Description": "R√ºckgabewert",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Creates a *closed* loop of curves based on a given list of points"
    }
  ],
  "Connectors": [
    {
      "Start": "918ae50b91cf47259db509c9cfc00df7",
      "End": "57356f9bf43341d6a987aed7574913c3",
      "Id": "6de66494a12a473eacbf518cfd4f0a58"
    },
    {
      "Start": "918ae50b91cf47259db509c9cfc00df7",
      "End": "90d7d1d8ec274bb397d574c27ec70a08",
      "Id": "951982408efc48f0ae72302a67b1bb05"
    },
    {
      "Start": "918ae50b91cf47259db509c9cfc00df7",
      "End": "031dafa2368542ec95734e03b67ec9d6",
      "Id": "b6e5648a592643ecbdcb0fe40142894d"
    },
    {
      "Start": "918ae50b91cf47259db509c9cfc00df7",
      "End": "e3071655713f45eea31618facc988e57",
      "Id": "cebfc42a8f19493089b57d3b02d67ce2"
    },
    {
      "Start": "b8d4cd4105654efdb5846c2029dda407",
      "End": "aac8cd0817204e4292f95e491ea8e988",
      "Id": "99bdb248d2814852a5d0999eeaa1efd5"
    },
    {
      "Start": "15e6315e36154c5a947efbb971f18d3f",
      "End": "8bfb349fd56e4bad8c612abeb53fe127",
      "Id": "3bafdcff0c83488f804682e9da11c69e"
    },
    {
      "Start": "659697cab2ff42d8ae75500195209c29",
      "End": "444107172e4d4bb0bca8be6241e413bf",
      "Id": "a15a18e8fe324ecdbea5640706f8a4bd"
    },
    {
      "Start": "b3e996821b9e4fa28e49877f402043ac",
      "End": "a58890fe27ac4c198eacc15d07c97b20",
      "Id": "d3d2fcd6c19147d496aab3f7bd0a7d6b"
    },
    {
      "Start": "3cb08e0c99f146729fb38281b66a403f",
      "End": "6b2093d9449b41d9b52d150f0ade8ce1",
      "Id": "6ff6942be0324be185ced2e5aeb334a4"
    },
    {
      "Start": "0163d8a6b32046ce8e318600f2e384ec",
      "End": "4af964687c3a49148c2c6fa12e6ced66",
      "Id": "9b8cea0529b84e26a4a9edf6c3814741"
    },
    {
      "Start": "0163d8a6b32046ce8e318600f2e384ec",
      "End": "e29f9a7fc7f64996997faa7e564b61aa",
      "Id": "1ab0b3c4da40487789a578d414f7c68d"
    }
  ],
  "Dependencies": [
    "576880d2-5f2c-4e34-9183-359361aaa077"
  ],
  "Bindings": [],
  "View": {
    "Dynamo": {
      "ScaleFactor": 1.0,
      "HasRunWithoutCrash": true,
      "IsVisibleInDynamoLibrary": true,
      "Version": "2.0.1.5055",
      "RunType": "Manual",
      "RunPeriod": "1000"
    },
    "Camera": {
      "Name": "Hintergrundvorschau",
      "EyeX": -17.0,
      "EyeY": 24.0,
      "EyeZ": 50.0,
      "LookX": 12.0,
      "LookY": -13.0,
      "LookZ": -58.0,
      "UpX": 0.0,
      "UpY": 1.0,
      "UpZ": 0.0
    },
    "NodeViews": [
      {
        "ShowGeometry": true,
        "Name": "Code Block",
        "Id": "84eb4267d7424dc8b663d2643ad140bf",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 0.0,
        "Y": 114.218333333333
      },
      {
        "ShowGeometry": true,
        "Name": "Point.ByCoordinates",
        "Id": "c3d18560a89f4cbf9dde858c1a7b9d38",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 185.0,
        "Y": 0.0
      },
      {
        "ShowGeometry": true,
        "Name": "Point.ByCoordinates",
        "Id": "6f02d94ddfcf4c58ae3ea011cb7ab0fa",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 185.0,
        "Y": 134.0
      },
      {
        "ShowGeometry": true,
        "Name": "Point.ByCoordinates",
        "Id": "8fe5b45aae6f4d46a231b15e5fe59fb7",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 185.0,
        "Y": 268.0
      },
      {
        "ShowGeometry": true,
        "Name": "Point.Origin",
        "Id": "b0583fafe5f843c08750b1de86bbcf28",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 236.767550702028,
        "Y": 392.8127925117
      },
      {
        "ShowGeometry": true,
        "Name": "List.Create",
        "Id": "ec3ec5237d54449eabc489df3b88791f",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 423.0,
        "Y": 108.0
      },
      {
        "ShowGeometry": true,
        "Name": "Watch",
        "Id": "ef6d8e2bd41f4c9baac5d0ed844bf4c8",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 954.0,
        "Y": 11.0
      },
      {
        "ShowGeometry": true,
        "Name": "Watch 3D",
        "Id": "c1a0c5e9831b4e0c8704652351045d80",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 954.0,
        "Y": 205.0
      },
      {
        "ShowGeometry": true,
        "Name": "Curve.ClosedLoopThroughPoints",
        "Id": "7e857513e74e46098f893ffaefac76fd",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 648.999552553258,
        "Y": 108.781311894691
      }
    ],
    "Annotations": [],
    "X": 30.0,
    "Y": 175.889871382637,
    "Zoom": 1.03054662379421
  }
}